# Generated by Django 4.2 on 2023-04-27 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_character_item_characteritem'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ManyToManyField(to='api.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hp', models.IntegerField()),
                ('armor', models.IntegerField()),
                ('magic_resists', models.IntegerField()),
                ('damage', models.IntegerField()),
                ('lvl', models.IntegerField()),
                ('loot', models.ManyToManyField(to='api.item')),
            ],
        ),
    ]
