# Generated by Django 4.2 on 2023-06-01 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_character_user_alter_resources_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorePotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('potion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.potion')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.store')),
            ],
        ),
        migrations.CreateModel(
            name='StoreCollectableItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('collectableItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.collectableitem')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.store')),
            ],
        ),
    ]
