# Generated by Django 4.2 on 2023-07-24 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_storepotion_storecollectableitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentPlayerHP', models.IntegerField()),
                ('currentEnemyHP', models.IntegerField()),
                ('isActive', models.BooleanField(default=False)),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.enemy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
