# Generated by Django 4.2 on 2023-05-02 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_item_weapon_type_item_armor_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='armor_type',
            new_name='item_type',
        ),
    ]
