# Generated by Django 4.2.1 on 2023-08-04 10:22

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_fight'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='imageUrl',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_to),
        ),
        migrations.AlterField(
            model_name='enemyloot',
            name='rarity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0001), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
