# Generated by Django 4.2 on 2023-05-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_armor_type_item_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteritem',
            name='slot',
            field=models.CharField(choices=[('helmet', 'helmet'), ('armor', 'armor'), ('gloves', 'gloves'), ('boots', 'gloves'), ('trousers', 'trousers'), ('weapon', 'weapon')], default='weapon', max_length=100),
        ),
    ]
