# Generated by Django 4.2.1 on 2023-10-09 20:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_transaction_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLvl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lvl', models.IntegerField(unique=True)),
                ('expPoints', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='enemy',
            name='exp',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='resources',
            name='lvl',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
