# Generated by Django 4.2.1 on 2024-08-08 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_resources_lvl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enemy',
            old_name='hp',
            new_name='health',
        ),
    ]
