# Generated by Django 4.2.1 on 2024-09-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_hp_enemy_health'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.TextField(default='region testowy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='description',
            field=models.TextField(default='testowy'),
            preserve_default=False,
        ),
    ]
