# Generated by Django 4.2.1 on 2024-09-04 20:28

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_location_description_region_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='imageUrl',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_to),
        ),
    ]
