# Generated by Django 4.2.1 on 2024-10-01 16:38

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_location_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='imgSrc',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_to),
        ),
    ]
