# Generated by Django 4.2.1 on 2024-11-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_enemy_imgsrc'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='xCoordinate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='yCoordinate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='isTraveling',
            field=models.BooleanField(default=False),
        ),
    ]
