# Generated by Django 4.2.1 on 2024-11-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_location_xcoordinate_location_ycoordinate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='xCoordinate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='yCoordinate',
            field=models.IntegerField(),
        ),
    ]
