# Generated by Django 4.2.1 on 2024-11-22 20:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_userlocation_istraveling_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlocation',
            name='travel_time',
        ),
        migrations.AddField(
            model_name='userlocation',
            name='travelTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 22, 20, 27, 50, 66858, tzinfo=datetime.timezone.utc)),
        ),
    ]
