# Generated by Django 4.2.1 on 2024-11-23 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_userlocation_travel_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='startTravelTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 23, 12, 27, 39, 510719, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='travelTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 23, 12, 27, 39, 510708, tzinfo=datetime.timezone.utc)),
        ),
    ]
