# Generated by Django 4.2.1 on 2024-11-29 20:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_userlocation_starttraveltime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='armor',
            new_name='baseArmor',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='damage',
            new_name='baseDamage',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='health',
            new_name='baseHealth',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='magicResist',
            new_name='baseMagicResist',
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='startTravelTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 29, 20, 33, 21, 343680, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='travelTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 29, 20, 33, 21, 343669, tzinfo=datetime.timezone.utc)),
        ),
    ]
