# Generated by Django 4.2.1 on 2024-11-25 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_userlocation_starttraveltime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='startTravelTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 25, 20, 45, 54, 974702, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='travelTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 25, 20, 45, 54, 974673, tzinfo=datetime.timezone.utc)),
        ),
    ]
