# Generated by Django 4.2.1 on 2024-11-30 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rename_armor_character_basearmor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='baseArmor',
            new_name='armor',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='baseDamage',
            new_name='damage',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='baseHealth',
            new_name='health',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='baseMagicResist',
            new_name='magicResist',
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='startTravelTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 30, 15, 23, 3, 749210, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='travelTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 30, 15, 23, 3, 749197, tzinfo=datetime.timezone.utc)),
        ),
    ]
