# Generated by Django 4.2.1 on 2024-11-30 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_rename_basearmor_character_armor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='startTravelTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 30, 19, 9, 41, 940826, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='travelTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 30, 19, 9, 41, 940814, tzinfo=datetime.timezone.utc)),
        ),
    ]
