# Generated by Django 4.2.1 on 2024-11-25 23:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_userlocation_starttraveltime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='xCoordinate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='location',
            name='yCoordinate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='startTravelTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 25, 23, 22, 44, 278010, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='travelTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 25, 23, 22, 44, 277981, tzinfo=datetime.timezone.utc)),
        ),
    ]
