# Generated by Django 4.2.1 on 2024-12-01 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_userlocation_starttraveltime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rarity',
            field=models.CharField(choices=[('common', 'common'), ('rare', 'rare'), ('mythic', 'mythic'), ('legendary', 'legendary')], default='common', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='startTravelTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 1, 12, 51, 57, 691909, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='travelTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 1, 12, 51, 57, 691897, tzinfo=datetime.timezone.utc)),
        ),
    ]
