# Generated by Django 4.2.1 on 2024-12-02 21:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_item_rarity_alter_userlocation_starttraveltime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='criticalHitChance',
            field=models.DecimalField(decimal_places=2, default=0.05, max_digits=5),
        ),
        migrations.AddField(
            model_name='character',
            name='criticalHitDamage',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=5),
        ),
        migrations.AddField(
            model_name='enemy',
            name='criticalHitChance',
            field=models.DecimalField(decimal_places=2, default=0.05, max_digits=5),
        ),
        migrations.AddField(
            model_name='enemy',
            name='criticalHitDamage',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=5),
        ),
        migrations.AddField(
            model_name='item',
            name='criticalHitChance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='item',
            name='criticalHitDamage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='startTravelTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 2, 21, 11, 44, 553743, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='travelTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 2, 21, 11, 44, 553731, tzinfo=datetime.timezone.utc)),
        ),
    ]
