# Generated by Django 4.2.1 on 2024-12-18 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_customuser_is_new_alter_userlocation_starttraveltime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='lvlRequired',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='startTravelTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 18, 18, 52, 58, 119090, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='travelTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 18, 18, 52, 58, 119079, tzinfo=datetime.timezone.utc)),
        ),
    ]
