# Generated by Django 4.2.1 on 2025-01-14 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_location_xcoordinate_and_more'),
        ('api', '0029_item_lvlrequired_alter_userlocation_starttraveltime_and_more'),
    ]

    operations = [
    ]
