# Generated by Django 4.2.1 on 2025-01-15 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_merge_20250115_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='startTravelTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 15, 18, 50, 51, 310201, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='travelTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 15, 18, 50, 51, 310188, tzinfo=datetime.timezone.utc)),
        ),
    ]
