# Generated by Django 4.2.1 on 2025-02-16 12:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0032_alter_userlocation_starttraveltime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('event_id', models.CharField(blank=True, max_length=100, null=True)),
                ('npc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogs', to='api.npc')),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('gold_reward', models.IntegerField(blank=True, null=True)),
                ('exp_reward', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('item_reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.item')),
            ],
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='startTravelTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 16, 12, 24, 46, 342141, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='travelTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 16, 12, 24, 46, 342130, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='QuestRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('kill', 'Kill'), ('collect', 'Collect'), ('explore', 'Explore')], max_length=10)),
                ('completed', models.BooleanField(default=False)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('target_object_id', models.PositiveIntegerField()),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='api.quest')),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='DialogOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('effects', models.JSONField(blank=True, null=True)),
                ('dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.dialog')),
                ('next_dialog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_options', to='api.dialog')),
            ],
        ),
        migrations.CreateModel(
            name='StoryState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'key')},
            },
        ),
    ]
