# Generated by Django 4.2.1 on 2025-03-09 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_remove_userquest_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questrequirement',
            name='is_last',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questrequirement',
            name='path',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='questrequirement',
            name='position',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='startTravelTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 9, 19, 20, 29, 861503, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='travelTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 9, 19, 20, 29, 861490, tzinfo=datetime.timezone.utc)),
        ),
    ]
