# Generated by Django 4.2.1 on 2025-03-10 15:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_questrequirement_is_last_questrequirement_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='startTravelTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 10, 15, 29, 6, 939341, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='travelTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 10, 15, 29, 6, 939330, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userquestrequirement',
            name='user_quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='api.userquest'),
        ),
    ]
