# Generated by Django 4.2.1 on 2025-03-10 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_userlocation_starttraveltime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='type',
            field=models.CharField(choices=[('main', 'main'), ('side', 'side')], default='main', max_length=10),
        ),
        migrations.AddField(
            model_name='userquestrequirement',
            name='amount_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='startTravelTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 10, 15, 47, 18, 863541, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='travelTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 10, 15, 47, 18, 863530, tzinfo=datetime.timezone.utc)),
        ),
    ]
