# Generated by Django 4.2.1 on 2025-03-17 22:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_quest_type_userquestrequirement_amount_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='location',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='api.location'),
        ),
        migrations.AlterField(
            model_name='questrequirement',
            name='type',
            field=models.CharField(choices=[('kill', 'Kill'), ('collect', 'Collect'), ('explore', 'Explore'), ('talk', 'Talk')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='startTravelTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 17, 22, 25, 13, 769812, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='travelTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 17, 22, 25, 13, 769799, tzinfo=datetime.timezone.utc)),
        ),
    ]
