# Generated by Django 4.2.1 on 2025-03-17 23:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_userlocation_starttraveltime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationelement',
            name='dialog_id',
        ),
        migrations.RemoveField(
            model_name='locationelement',
            name='enemy_id',
        ),
        migrations.AddField(
            model_name='locationelement',
            name='enemy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.enemy'),
        ),
        migrations.AddField(
            model_name='locationelement',
            name='npc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.npc'),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='startTravelTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 17, 23, 1, 15, 524518, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='travelTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 17, 23, 1, 15, 524507, tzinfo=datetime.timezone.utc)),
        ),
    ]
