# Generated by Django 4.2.1 on 2025-03-17 23:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_remove_locationelement_dialog_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationelement',
            name='name',
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='startTravelTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 17, 23, 4, 18, 588869, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='travelTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 17, 23, 4, 18, 588857, tzinfo=datetime.timezone.utc)),
        ),
    ]
