# Generated by Django 4.2.1 on 2025-03-20 21:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_remove_locationelement_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialog',
            name='starter',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='startTravelTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 20, 21, 46, 12, 405391, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='travelTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 20, 21, 46, 12, 405379, tzinfo=datetime.timezone.utc)),
        ),
    ]
