# Generated by Django 4.2.1 on 2025-03-22 19:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_dialog_starter_alter_userlocation_starttraveltime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationelement',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.item'),
        ),
        migrations.AlterField(
            model_name='locationelement',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.location'),
        ),
        migrations.AlterField(
            model_name='locationelement',
            name='type',
            field=models.CharField(choices=[('npc', 'NPC'), ('enemy', 'Enemy'), ('object', 'Interactive Object'), ('item', 'Item'), ('location', 'Location')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='startTravelTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 22, 19, 17, 57, 286682, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='travelTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 22, 19, 17, 57, 286670, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterUniqueTogether(
            name='dialog',
            unique_together={('npc', 'starter')},
        ),
    ]
