# Generated by Django 4.2.1 on 2025-03-22 19:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_locationelement_item_alter_locationelement_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationelement',
            name='location_element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.location'),
        ),
        migrations.AlterField(
            model_name='locationelement',
            name='location',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='api.location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='startTravelTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 22, 19, 33, 42, 362058, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='travelTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 22, 19, 33, 42, 362046, tzinfo=datetime.timezone.utc)),
        ),
    ]
