# Generated by Django 4.2.1 on 2025-03-24 08:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_alter_locationelement_location_element_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationelement',
            name='location_element',
        ),
        migrations.AlterField(
            model_name='locationelement',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='api.location'),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='startTravelTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 24, 8, 8, 8, 347436, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='travelTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 24, 8, 8, 8, 347423, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='SubLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('imageUrl', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('parent_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sublocations', to='api.location')),
            ],
        ),
        migrations.AddField(
            model_name='locationelement',
            name='sublocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='api.sublocation'),
        ),
    ]
