# Generated by Django 4.2.1 on 2025-03-24 09:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_remove_locationelement_location_element_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationelement',
            name='location_element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.location'),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='startTravelTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 24, 9, 20, 13, 98226, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='travelTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 24, 9, 20, 13, 98215, tzinfo=datetime.timezone.utc)),
        ),
    ]
