# Generated by Django 4.2.1 on 2025-03-24 09:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_locationelement_location_element_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationelement',
            name='sublocation_element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sublocation'),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='startTravelTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 24, 9, 33, 16, 202268, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='travelTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 24, 9, 33, 16, 202257, tzinfo=datetime.timezone.utc)),
        ),
    ]
