# Generated by Django 4.2.1 on 2025-03-24 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_locationelement_sublocation_element_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dialog',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='startTravelTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 24, 15, 37, 18, 835237, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='travelTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 24, 15, 37, 18, 835227, tzinfo=datetime.timezone.utc)),
        ),
    ]
