# Generated by Django 4.2 on 2023-04-27 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_useritems_enemy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteritem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.item'),
        ),
        migrations.AlterField(
            model_name='useritems',
            name='item',
            field=models.ManyToManyField(blank=True, to='api.item'),
        ),
    ]
