# Generated by Django 4.2 on 2023-05-03 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_characteritem_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteritem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.item'),
        ),
    ]
