# Generated by Django 4.2 on 2023-05-15 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_characteritem_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='magic_resist',
            new_name='magicResist',
        ),
        migrations.RenameField(
            model_name='enemy',
            old_name='magic_resists',
            new_name='magicResist',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='magic_resist',
            new_name='magicResist',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_type',
        ),
        migrations.AddField(
            model_name='item',
            name='itemType',
            field=models.CharField(choices=[('helmet', 'helmet'), ('armor', 'armor'), ('gloves', 'gloves'), ('boots', 'boots'), ('trousers', 'trousers'), ('weapon', 'weapon')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='damage',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='health',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='characteritem',
            name='slot',
            field=models.CharField(choices=[('helmet', 'helmet'), ('armor', 'armor'), ('gloves', 'gloves'), ('boots', 'boots'), ('trousers', 'trousers'), ('weapon', 'weapon')], default='weapon', max_length=100),
        ),
    ]
