# Generated by Django 4.2.1 on 2023-05-31 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_region_location_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectableItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('goldValue', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Potion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hpValue', models.IntegerField()),
                ('goldValue', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='location',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.region'),
        ),
        migrations.RemoveField(
            model_name='useritems',
            name='item',
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.location'),
        ),
        migrations.CreateModel(
            name='UserPotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('potion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.potion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCollectableItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('collectableItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.collectableitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='useritems',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.item'),
            preserve_default=False,
        ),
    ]
